#ifndef VIEWRECT_H
#define VIEWRECT_H

#include <queue>

#include <Ultralight/Ultralight.h>

#include <godot_cpp/classes/control.hpp>
#include <godot_cpp/classes/input_event.hpp>
#include <godot_cpp/classes/input_event_mouse_motion.hpp>
#include <godot_cpp/classes/input_event_mouse_button.hpp>
#include <godot_cpp/classes/input_event_key.hpp>
#include <godot_cpp/classes/image.hpp>
#include <godot_cpp/classes/image_texture.hpp>


namespace godot {

    class ViewRect : public Control, public ultralight::ViewListener, public ultralight::LoadListener {
        GDCLASS(ViewRect, Control);

        private:
            enum Event { mouse, key, scroll };
            std::queue<Event> events;
            std::queue<ultralight::MouseEvent> mouse_events;
            std::queue<ultralight::KeyEvent> key_events;
            std::queue<ultralight::ScrollEvent> scroll_events;

            ultralight::RefPtr<ultralight::View> view; // Ultralight view
            ultralight::RefPtr<ultralight::View> inspector_view; // Ultralight Inspector view

            Ref<ImageTexture> image_texture;
            Ref<Image> image;

            void HandleMouseButton(InputEventMouseButton* event);
            void HandleMouseMotion(InputEventMouseMotion* event);
            void HandleKey(InputEventKey* event);

            void RenderFrame();
            void SizeChanged();

            void CopyBitmapToTexture(ultralight::RefPtr<ultralight::Bitmap> bitmap);

            // ViewListener overrides.
            ultralight::RefPtr<ultralight::View> OnCreateInspectorView(ultralight::View *caller, bool is_local, const ultralight::String &inspected_url) override;
            void OnChangeCursor(ultralight::View *caller, ultralight::Cursor cursor) override;

        protected:
            static void _bind_methods();

        public:
            ViewRect();
            ~ViewRect();

            void SetView(ultralight::RefPtr<ultralight::View> p_view);
             ultralight::RefPtr<ultralight::View> GetView();

            ultralight::RefPtr<ultralight::View> GetInspectorView();

            void _process(double delta) override;
            void _gui_input(const Ref<InputEvent> &event) override;
            void _draw() override;
            // void _notification(int what);

            // ALERT: Map generated by Claude AI. Someone should probably double check this. 😳
            const std::unordered_map<ultralight::Cursor, CursorShape> CursorMap = {
                {ultralight::Cursor::kCursor_Pointer, CursorShape::CURSOR_ARROW},
                {ultralight::Cursor::kCursor_IBeam, CursorShape::CURSOR_IBEAM},
                {ultralight::Cursor::kCursor_Hand, CursorShape::CURSOR_POINTING_HAND},
                {ultralight::Cursor::kCursor_Cross, CursorShape::CURSOR_CROSS},
                {ultralight::Cursor::kCursor_Wait, CursorShape::CURSOR_WAIT},
                {ultralight::Cursor::kCursor_Progress, CursorShape::CURSOR_BUSY},
                {ultralight::Cursor::kCursor_Grabbing, CursorShape::CURSOR_DRAG},
                {ultralight::Cursor::kCursor_Copy, CursorShape::CURSOR_CAN_DROP},
                {ultralight::Cursor::kCursor_NotAllowed, CursorShape::CURSOR_FORBIDDEN},
                {ultralight::Cursor::kCursor_NorthSouthResize, CursorShape::CURSOR_VSIZE},
                {ultralight::Cursor::kCursor_EastWestResize, CursorShape::CURSOR_HSIZE},
                {ultralight::Cursor::kCursor_NorthWestSouthEastResize, CursorShape::CURSOR_BDIAGSIZE},
                {ultralight::Cursor::kCursor_NorthEastSouthWestResize, CursorShape::CURSOR_FDIAGSIZE},
                {ultralight::Cursor::kCursor_Move, CursorShape::CURSOR_MOVE},
                {ultralight::Cursor::kCursor_RowResize, CursorShape::CURSOR_VSPLIT},
                {ultralight::Cursor::kCursor_ColumnResize, CursorShape::CURSOR_HSPLIT},
                {ultralight::Cursor::kCursor_Help, CursorShape::CURSOR_HELP},
            };

            // ALERT: Map generated by Claude AI. Someone should probably double check this. 😳
            const std::unordered_map<int, int> KeyMap = {
                {Key::KEY_NONE, ultralight::KeyCodes::GK_UNKNOWN},
                {Key::KEY_ESCAPE, ultralight::KeyCodes::GK_ESCAPE},
                {Key::KEY_TAB, ultralight::KeyCodes::GK_TAB},
                {Key::KEY_BACKTAB, ultralight::KeyCodes::GK_TAB}, // No direct equivalent, mapping to TAB
                {Key::KEY_BACKSPACE, ultralight::KeyCodes::GK_BACK},
                {Key::KEY_ENTER, ultralight::KeyCodes::GK_RETURN},
                {Key::KEY_KP_ENTER, ultralight::KeyCodes::GK_RETURN},
                {Key::KEY_INSERT, ultralight::KeyCodes::GK_INSERT},
                {Key::KEY_DELETE, ultralight::KeyCodes::GK_DELETE},
                {Key::KEY_PAUSE, ultralight::KeyCodes::GK_PAUSE},
                {Key::KEY_PRINT, ultralight::KeyCodes::GK_PRINT},
                {Key::KEY_SYSREQ, ultralight::KeyCodes::GK_SNAPSHOT}, // Closest equivalent
                {Key::KEY_CLEAR, ultralight::KeyCodes::GK_CLEAR},
                {Key::KEY_HOME, ultralight::KeyCodes::GK_HOME},
                {Key::KEY_END, ultralight::KeyCodes::GK_END},
                {Key::KEY_LEFT, ultralight::KeyCodes::GK_LEFT},
                {Key::KEY_UP, ultralight::KeyCodes::GK_UP},
                {Key::KEY_RIGHT, ultralight::KeyCodes::GK_RIGHT},
                {Key::KEY_DOWN, ultralight::KeyCodes::GK_DOWN},
                {Key::KEY_PAGEUP, ultralight::KeyCodes::GK_PRIOR},
                {Key::KEY_PAGEDOWN, ultralight::KeyCodes::GK_NEXT},
                {Key::KEY_SHIFT, ultralight::KeyCodes::GK_SHIFT},
                {Key::KEY_CTRL, ultralight::KeyCodes::GK_CONTROL},
                {Key::KEY_META, ultralight::KeyCodes::GK_LWIN}, // Assuming META is Windows key
                {Key::KEY_ALT, ultralight::KeyCodes::GK_MENU},
                {Key::KEY_CAPSLOCK, ultralight::KeyCodes::GK_CAPITAL},
                {Key::KEY_NUMLOCK, ultralight::KeyCodes::GK_NUMLOCK},
                {Key::KEY_SCROLLLOCK, ultralight::KeyCodes::GK_SCROLL},
                {Key::KEY_F1, ultralight::KeyCodes::GK_F1},
                {Key::KEY_F2, ultralight::KeyCodes::GK_F2},
                {Key::KEY_F3, ultralight::KeyCodes::GK_F3},
                {Key::KEY_F4, ultralight::KeyCodes::GK_F4},
                {Key::KEY_F5, ultralight::KeyCodes::GK_F5},
                {Key::KEY_F6, ultralight::KeyCodes::GK_F6},
                {Key::KEY_F7, ultralight::KeyCodes::GK_F7},
                {Key::KEY_F8, ultralight::KeyCodes::GK_F8},
                {Key::KEY_F9, ultralight::KeyCodes::GK_F9},
                {Key::KEY_F10, ultralight::KeyCodes::GK_F10},
                {Key::KEY_F11, ultralight::KeyCodes::GK_F11},
                {Key::KEY_F12, ultralight::KeyCodes::GK_F12},
                {Key::KEY_F13, ultralight::KeyCodes::GK_F13},
                {Key::KEY_F14, ultralight::KeyCodes::GK_F14},
                {Key::KEY_F15, ultralight::KeyCodes::GK_F15},
                {Key::KEY_F16, ultralight::KeyCodes::GK_F16},
                {Key::KEY_KP_MULTIPLY, ultralight::KeyCodes::GK_MULTIPLY},
                {Key::KEY_KP_DIVIDE, ultralight::KeyCodes::GK_DIVIDE},
                {Key::KEY_KP_SUBTRACT, ultralight::KeyCodes::GK_SUBTRACT},
                {Key::KEY_KP_PERIOD, ultralight::KeyCodes::GK_DECIMAL},
                {Key::KEY_KP_ADD, ultralight::KeyCodes::GK_ADD},
                {Key::KEY_KP_0, ultralight::KeyCodes::GK_NUMPAD0},
                {Key::KEY_KP_1, ultralight::KeyCodes::GK_NUMPAD1},
                {Key::KEY_KP_2, ultralight::KeyCodes::GK_NUMPAD2},
                {Key::KEY_KP_3, ultralight::KeyCodes::GK_NUMPAD3},
                {Key::KEY_KP_4, ultralight::KeyCodes::GK_NUMPAD4},
                {Key::KEY_KP_5, ultralight::KeyCodes::GK_NUMPAD5},
                {Key::KEY_KP_6, ultralight::KeyCodes::GK_NUMPAD6},
                {Key::KEY_KP_7, ultralight::KeyCodes::GK_NUMPAD7},
                {Key::KEY_KP_8, ultralight::KeyCodes::GK_NUMPAD8},
                {Key::KEY_KP_9, ultralight::KeyCodes::GK_NUMPAD9},
                {Key::KEY_MENU, ultralight::KeyCodes::GK_MENU},
                {Key::KEY_HELP, ultralight::KeyCodes::GK_HELP},
                {Key::KEY_BACK, ultralight::KeyCodes::GK_BROWSER_BACK},
                {Key::KEY_FORWARD, ultralight::KeyCodes::GK_BROWSER_FORWARD},
                {Key::KEY_STOP, ultralight::KeyCodes::GK_BROWSER_STOP},
                {Key::KEY_REFRESH, ultralight::KeyCodes::GK_BROWSER_REFRESH},
                {Key::KEY_VOLUMEDOWN, ultralight::KeyCodes::GK_VOLUME_DOWN},
                {Key::KEY_VOLUMEMUTE, ultralight::KeyCodes::GK_VOLUME_MUTE},
                {Key::KEY_VOLUMEUP, ultralight::KeyCodes::GK_VOLUME_UP},
                {Key::KEY_MEDIAPLAY, ultralight::KeyCodes::GK_MEDIA_PLAY_PAUSE},
                {Key::KEY_MEDIASTOP, ultralight::KeyCodes::GK_MEDIA_STOP},
                {Key::KEY_MEDIAPREVIOUS, ultralight::KeyCodes::GK_MEDIA_PREV_TRACK},
                {Key::KEY_MEDIANEXT, ultralight::KeyCodes::GK_MEDIA_NEXT_TRACK},
                {Key::KEY_HOMEPAGE, ultralight::KeyCodes::GK_BROWSER_HOME},
                {Key::KEY_FAVORITES, ultralight::KeyCodes::GK_BROWSER_FAVORITES},
                {Key::KEY_SEARCH, ultralight::KeyCodes::GK_BROWSER_SEARCH},
                {Key::KEY_STANDBY, ultralight::KeyCodes::GK_SLEEP},
                {Key::KEY_LAUNCHMAIL, ultralight::KeyCodes::GK_MEDIA_LAUNCH_MAIL},
                {Key::KEY_LAUNCHMEDIA, ultralight::KeyCodes::GK_MEDIA_LAUNCH_MEDIA_SELECT},
                {Key::KEY_LAUNCH0, ultralight::KeyCodes::GK_MEDIA_LAUNCH_APP1},
                {Key::KEY_LAUNCH1, ultralight::KeyCodes::GK_MEDIA_LAUNCH_APP2},
                {Key::KEY_SPACE, ultralight::KeyCodes::GK_SPACE},
                {Key::KEY_EXCLAM, ultralight::KeyCodes::GK_OEM_1},
                {Key::KEY_QUOTEDBL, ultralight::KeyCodes::GK_OEM_7},
                {Key::KEY_NUMBERSIGN, ultralight::KeyCodes::GK_OEM_3},
                {Key::KEY_DOLLAR, ultralight::KeyCodes::GK_OEM_4},
                {Key::KEY_PERCENT, ultralight::KeyCodes::GK_OEM_5},
                {Key::KEY_AMPERSAND, ultralight::KeyCodes::GK_OEM_6},
                {Key::KEY_APOSTROPHE, ultralight::KeyCodes::GK_OEM_7},
                {Key::KEY_PARENLEFT, ultralight::KeyCodes::GK_OEM_4},
                {Key::KEY_PARENRIGHT, ultralight::KeyCodes::GK_OEM_6},
                {Key::KEY_ASTERISK, ultralight::KeyCodes::GK_OEM_2},
                {Key::KEY_PLUS, ultralight::KeyCodes::GK_OEM_PLUS},
                {Key::KEY_COMMA, ultralight::KeyCodes::GK_OEM_COMMA},
                {Key::KEY_MINUS, ultralight::KeyCodes::GK_OEM_MINUS},
                {Key::KEY_PERIOD, ultralight::KeyCodes::GK_OEM_PERIOD},
                {Key::KEY_SLASH, ultralight::KeyCodes::GK_OEM_2},
                {Key::KEY_0, ultralight::KeyCodes::GK_0},
                {Key::KEY_1, ultralight::KeyCodes::GK_1},
                {Key::KEY_2, ultralight::KeyCodes::GK_2},
                {Key::KEY_3, ultralight::KeyCodes::GK_3},
                {Key::KEY_4, ultralight::KeyCodes::GK_4},
                {Key::KEY_5, ultralight::KeyCodes::GK_5},
                {Key::KEY_6, ultralight::KeyCodes::GK_6},
                {Key::KEY_7, ultralight::KeyCodes::GK_7},
                {Key::KEY_8, ultralight::KeyCodes::GK_8},
                {Key::KEY_9, ultralight::KeyCodes::GK_9},
                {Key::KEY_COLON, ultralight::KeyCodes::GK_OEM_1},
                {Key::KEY_SEMICOLON, ultralight::KeyCodes::GK_OEM_1},
                {Key::KEY_LESS, ultralight::KeyCodes::GK_OEM_COMMA},
                {Key::KEY_EQUAL, ultralight::KeyCodes::GK_OEM_PLUS},
                {Key::KEY_GREATER, ultralight::KeyCodes::GK_OEM_PERIOD},
                {Key::KEY_QUESTION, ultralight::KeyCodes::GK_OEM_2},
                {Key::KEY_AT, ultralight::KeyCodes::GK_OEM_3},
                {Key::KEY_A, ultralight::KeyCodes::GK_A},
                {Key::KEY_B, ultralight::KeyCodes::GK_B},
                {Key::KEY_C, ultralight::KeyCodes::GK_C},
                {Key::KEY_D, ultralight::KeyCodes::GK_D},
                {Key::KEY_E, ultralight::KeyCodes::GK_E},
                {Key::KEY_F, ultralight::KeyCodes::GK_F},
                {Key::KEY_G, ultralight::KeyCodes::GK_G},
                {Key::KEY_H, ultralight::KeyCodes::GK_H},
                {Key::KEY_I, ultralight::KeyCodes::GK_I},
                {Key::KEY_J, ultralight::KeyCodes::GK_J},
                {Key::KEY_K, ultralight::KeyCodes::GK_K},
                {Key::KEY_L, ultralight::KeyCodes::GK_L},
                {Key::KEY_M, ultralight::KeyCodes::GK_M},
                {Key::KEY_N, ultralight::KeyCodes::GK_N},
                {Key::KEY_O, ultralight::KeyCodes::GK_O},
                {Key::KEY_P, ultralight::KeyCodes::GK_P},
                {Key::KEY_Q, ultralight::KeyCodes::GK_Q},
                {Key::KEY_R, ultralight::KeyCodes::GK_R},
                {Key::KEY_S, ultralight::KeyCodes::GK_S},
                {Key::KEY_T, ultralight::KeyCodes::GK_T},
                {Key::KEY_U, ultralight::KeyCodes::GK_U},
                {Key::KEY_V, ultralight::KeyCodes::GK_V},
                {Key::KEY_W, ultralight::KeyCodes::GK_W},
                {Key::KEY_X, ultralight::KeyCodes::GK_X},
                {Key::KEY_Y, ultralight::KeyCodes::GK_Y},
                {Key::KEY_Z, ultralight::KeyCodes::GK_Z},
                {Key::KEY_BRACKETLEFT, ultralight::KeyCodes::GK_OEM_4},
                {Key::KEY_BACKSLASH, ultralight::KeyCodes::GK_OEM_5},
                {Key::KEY_BRACKETRIGHT, ultralight::KeyCodes::GK_OEM_6},
                {Key::KEY_ASCIICIRCUM, ultralight::KeyCodes::GK_OEM_5},
                {Key::KEY_UNDERSCORE, ultralight::KeyCodes::GK_OEM_MINUS},
                {Key::KEY_QUOTELEFT, ultralight::KeyCodes::GK_OEM_3},
                {Key::KEY_BRACELEFT, ultralight::KeyCodes::GK_OEM_4},
                {Key::KEY_BAR, ultralight::KeyCodes::GK_OEM_5},
                {Key::KEY_BRACERIGHT, ultralight::KeyCodes::GK_OEM_6},
                {Key::KEY_ASCIITILDE, ultralight::KeyCodes::GK_OEM_3},
            };
    
            const std::unordered_map<uint64_t, uint8_t> ModifierMap = {
                {KEY_MASK_ALT, ultralight::KeyEvent::kMod_AltKey},
                {KEY_MASK_CTRL, ultralight::KeyEvent::kMod_CtrlKey},
                {KEY_MASK_META, ultralight::KeyEvent::kMod_MetaKey},
                {KEY_MASK_SHIFT, ultralight::KeyEvent::kMod_ShiftKey},
                {KEY_MASK_CMD_OR_CTRL, ultralight::KeyEvent::kMod_CtrlKey}  // Mapping CMD_OR_CTRL to Ctrl for simplicity
            };
    };

}

#endif
